# Rebinding Prefix/Leader key to <Control> + <Space>
#unbind C-b

#set -g prefix C-Space

# Enable mouse within tmux
# Allows: 1) Selecting windows (via tabs in status line)
#         2) Selcting, scrolling, resizing panes
#         3) Copying text
set -g mouse on

# Adds binds to 'v' and 'h' for splitting panes; '-c' executes new pane in current directory
# bind v split-window -c
# bind h split-window -c

# Resizing panes
# ADD IF NEEDED

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Color Themes
set -g @plugin "arcticicestudio/nord-tmux"

# Initialize and run tpm
run "~/.tmux/plugins/tpm/tpm
